version: "2"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo:/data/db
  api:
    build: .
    ports:
     - 4242:4242
    environment:
      PORT: 4242
      MONGO_HOST: mongo
      JWT_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUURaSGNUNXZnUkxyTS9GSGlDNGl4V00wMGdlakI0TFZabVpxY0M1dEM0cjhKcmZCWFhqCmRDeGVUd0NWekJPZ3lwMmp1bmY0RlBuODNNb1g4WThhY0NlTlBNVGR6L1pRcUQvQUdvSGVsekovM1pFcm11bDgKLzcvWlJXaUJlNGltb2h6aWFJdVNFNFl4TWNlU1pESE5FelZPVE5pcmRKSGtSWVZmOHVmMDEwMHdXUUlEQVFBQgpBb0dBVHNVM0xxaWE1RjI1TDduamd6Q3F5K0hudTNWNGZRSThiUHlpZUgxL2R0K2ZRS1M1aGFFamE3L2I1WDBaCjdlODB6QzhkMFhyQ3k5UEsybThBVFVZOWdweGkxNXVBZTArS2wzZXRMMGk5TThJMVVuWVRPWXJWanVvSGZuWjUKRDEwSC9uNm1MeksxSlBRdjVLRzlmL0Fjek1zRS9vdGtjelA5VGcrdUpyZEhIQ1VDUVFEdDdnS3h1bTF6Q3g1cQplZ3FCcTBiWVV3RVF5ZjlIenZqOVBDa2orYXVoSXA1dkI3N2ozZ2dtUXBqa0lzb3ROd21XbmhFTWszdUpON2F5CnNTajd4VzlyQWtFQTZac1hDcmxFa2lmWE5MNm9pSmo0ditURFUxc3MwUnpHVVN0M3VqS00wUHlObksxVkRpc3gKM3NETDMvZVFuUzVKOThvcEROZklWQk4vczhnV3VYK2tTd0pBUE9BbzBGQmlzSXludTVaK0dhODQ4U0JMcFlBSgpVTllqM3FjRjM2NkJ1emlnVU1ncWp5Sy84d29YRkVmU2NyOGlOT2M4ZFh0R29GVWc2WmRxWlFDZkFRSkFTSzBrClpRU3dqWnZ4ZXdwWjJtMWs3aVpZa2tWS1V5QlZub2tjYllRdWhSSWRhSUlRZFNFQkdlRDNUSTF6bzBMMFppK3gKeDdvV0svb0kvOENmT1VTNXN3SkJBSWkwZFFNTVNkTkhmRXJ2REZKYlR3ZTRRQ2RkeWhHMUlMQ3hjZlZnaG9WeApnRDJJOFptN0JzRGh3T3UyWWRKRU5nQzJvWURHZ0wrMEdrZkJWOWVRTkVRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
      JWT_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FEWkhjVDV2Z1JMck0vRkhpQzRpeFdNMDBnZQpqQjRMVlptWnFjQzV0QzRyOEpyZkJYWGpkQ3hlVHdDVnpCT2d5cDJqdW5mNEZQbjgzTW9YOFk4YWNDZU5QTVRkCnovWlFxRC9BR29IZWx6Si8zWkVybXVsOC83L1pSV2lCZTRpbW9oemlhSXVTRTRZeE1jZVNaREhORXpWT1ROaXIKZEpIa1JZVmY4dWYwMTAwd1dRSURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
    links:
      - mongo
    volumes:
      - ./:/go/src/github.com/cruux/api
